[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
arch_locker = "2jDqQUZY7yidwa8DTQm6vyFcptFPZ4QhxJn5ePGpgd2p"

[programs.devnet]
arch_locker = "2jDqQUZY7yidwa8DTQm6vyFcptFPZ4QhxJn5ePGpgd2p"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
