[workspace]
members = ["programs/arch_locker"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = { version = "=1.0.2", features = ["init-if-needed"] }
anchor-spl = { version = "=1.0.2", default-features = false, features = ["associated_token", "metadata", "token", "token_2022", "token_2022_extensions"] }
anchor-attribute-access-control = "=1.0.2"
anchor-attribute-account = "=1.0.2"
anchor-attribute-constant = "=1.0.2"
anchor-attribute-error = "=1.0.2"
anchor-attribute-event = "=1.0.2"
anchor-attribute-program = "=1.0.2"
anchor-derive-accounts = "=1.0.2"
anchor-derive-serde = "=1.0.2"
anchor-derive-space = "=1.0.2"
anchor-syn = "=1.0.2"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(target_os, values("solana"))',
] }

[workspace.metadata.cli]
solana = "3.1.10"
